[project]
name = "mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.0",
    "fastapi-mcp>=0.4.0",
    "fastmcp>=2.12.5",
    "uvicorn[standard]>=0.38.0",
]
